name: Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: yardinternet/workflows/.github/workflows/run-laravel-testbench-tests.yml@poc/spatie-matrix
    with:
      laravel-versions: '["10.*","12.*"]'
    secrets: inherit
